config/routes.rb
Rails.application.routes.draw do
	# get "/", to:"welcome#index"
	root "welcome#index"
	resources :candidates do 
		member do
			post :vote
		end
	end
	# post "/candidates/:id/vote". to: "candidates#vote"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
	validates :name, presence: true
	has_many :vote_logs


	def info
		"#{name}, (年紀:#{age}, 政黨:#{party})"
	end

end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
# rails g model VoteLog ip_address candidate_id:integer
# rails g model VoteLog ip_address candidate:references

class CandidatesController < ApplicationController

	# before_action :find_candidate, only: [:show, :edit, :update, :destroy]

	def index
		@candidates = Candidate.all  #慣例上會給複數
	end	

	def show
		@candidate = Candidate.find_by(id:params[:id])
		redirect_to candidates_path if @candidate.nil?
		# @candidate = Candidate.find(params[:id])
	end

	def edit
		@candidate = Candidate.find_by(id:params[:id])
		redirect_to candidates_path if @candidate.nil?
	end

	def update
		@candidate = Candidate.find_by(id:params[:id])
			flash[:notice]= "done update"
		redirect_to candidates_path if @candidate.nil?
		if @candidate.update(candidate_params)
			redirect_to candidates_path
		else
			render "edit"
		end
	end

	def destroy
		@candidate = Candidate.find_by(id:params[:id])
		redirect_to candidates_path if @candidate.nil?
		
		@candidate.destroy
		redirect_to candidate_path
	end

	def vote
	  # log = VoteLog.new(ip_address: request.remote_ip, candidate: @candidate)
	  # log.save
	  @candidate = Candidate.find_by(id:params[:id])
	  @candidate.vote_logs.create(ip_address: request.remote_ip)
      @candidate.increment(:votes)
      @candidate.save
      redirect_to candidates_path, notice: "完成投票!"
    end

	def new
		@candidate = Candidate.new
	end

	def create
		@candidate = Candidate.new(candidate_params)
		if @candidate.save
			redirect_to candidates_path
		else
			render :new
			# redirect_to new_candidate_path? name=""&party=".."
			#....
		end

	end	

	private
	def candidate_params
		params.require(:candidate).permit(:name, :party, :age, :politics)
	end
end

app/controllers/welcome_controller.rb
# class WelcomeController < ApplicationController
# 	def index
# 	end
# end
Rails.application.routes.draw do

	root "welcome#index"
	resources :candidates
	# get "/candidates", to: "cancandidates#index"
	# get "/candidates/:id" to: "cancandidates#show"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<!-- 可把edit跟new的貼過來 做整理 -->

app/views/candidates/edit.html.erb
<h1>候選人edited</h1>

<% if @candidate.errors.any? %>
	<% @candidate.errors.full_messages.each do |msg| %>
		<%= msg %>
	<% end %>
<% end %>

<%= form_for @candidate do |f| %>

	姓名: <%= f.text_field :name %><br/>
	政黨: <%= f.text_field :party %><br/>
	年紀: <%= f.text_field :age %><br/>
	政見: <%= f.text_field :politics %><br/>
	<%= f.submit %><br/>
<% end %>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>

<%= link_to '新增候選人', new_candidate_path %>



<ul>
<% @candidates.each do |candidate| %>
	<li>
	<%= candidate.vote_logs.count  %>票
	<%= link_to '投票', vote_candidate_path(candidate), method: "post", data: {confirm: "Are you sure to vote?"} %>
	<%= link_to candidate.info, candidate_path(candidate)  %>
	<%= link_to	candidate.name, candidate_path(candidate) %>
	<%= link_to '編輯', edit_candidate_path(candidate) %>
	<%= link_to '刪除', candidate_path(candidate), method: "delete", data: {confirm: "Are you sure to delete?"} %>
	</li>
<% end %>
</ul>

app/views/candidates/new.html.erb
<h1>候選人列表</h1>

<% if @candidate.errors.any? %>
	<% @candidate.errors.full_messages.each do |msg| %>
		<%= msg %>
	<% end %>
<% end %>

<%= form_for @candidate do |f| %>

	姓名: <%= f.text_field :name %><br/>
	政黨: <%= f.text_field :party %><br/>
	年紀: <%= f.text_field :age %><br/>
	政見: <%= f.text_field :politics %><br/>
	<%= f.submit %><br/>
<% end %>

app/views/candidates/show.html.erb
<h1><%= @candidate.name %></h1>

政黨: <%= @candidate.party %><br/>
年紀: <%= @candidate.age %><br/>
政見: <%= @candidate.politics %><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCandidate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>yoyoyoyoyoyoy</h1>